apiVersion: v1
kind: Service
metadata:
  name: gel-app-node-port-srv
spec:
  type: NodePort
  selector:
    app: gel-app
  ports:
    - name: client
      protocol: TCP
      port: 4000
      targetPort: 4000
      